//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mart.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoldYearEntity : DbContext
    {
        public SoldYearEntity()
            : base("name=SoldYearEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public virtual ObjectResult<GetSoldByYear_Result> GetSoldByYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSoldByYear_Result>("GetSoldByYear");
        }
    }
}
